### ISSUE TITLE
`validate()` calls `get_version()` with argument of wrong type: nbjson instead of nbdict

### ISSUE THREAD

**Issue by wstomv** [jupyter/nbformat#112]
`validate()` in https://github.com/jupyter/nbformat/blob/master/nbformat/validator.py calls `get_version(nbjson)`, but `get_version()` expects a notebook in dictionary form, and not a JSON string.

Extracting the (expected) version from the JSON string is already a bit suspicious, because validation still has to take place, and possibly the JSON string does not conform to a notebook schema.

**Comment by takluyver** [comment]
I think this is just bad naming & documenting. Everywhere I can see in our code that calls `validate()` passes it an already-parsed notebook object (`NotebookNode`, which is basically a dict), not a JSON string. I think that's how we always intended it to be used.

**Comment by wstomv** [comment]
Thanks for clarifying.

It would help to rename the `nbjson` parameter in `validate()` and (especially) update the docstring (which now specifically mentions `notebook JSON`).

**Comment by takluyver** [comment]
Updating the docstring definitely makes sense. Changing the parameter name is technically breaking API, because all parameters can be passed by keyword in Python - but I think our code all passes it positionally. I'd be -0.5 on changing the parameter, but others may disagree.

Do you want to make a PR?

**Comment by wstomv** [comment]
I currently don't have the time to handle PRs on this.

**Comment by mpacer** [comment]
Is there a reason not to just read it into memory if we know the major version number?

**Comment by mpacer** [comment]
If the keyword trick is the only reason not to change the value… there's actually a pretty easy fix to changing the value (adding it as an additional keyword argument and an alternative code path)… i'll implement to show what i mean

**Comment by jasongrout** [comment]
Closed by #116.
