### ISSUE TITLE
cell.metadata.name is stated to be globally unique but that is not represented in the schema

### ISSUE THREAD

**Issue by mpacer** [jupyter/nbformat#114]
Currently the description includes a comment about cell names being unique across a notebook's cells: 
https://github.com/jupyter/nbformat/blob/6fdb508eb2fbb724ae4a83d737e6a264d165fa3e/nbformat/v4/nbformat.v4.schema.json#L366-L370

There is no constraint expressed that enforces that uniqueness across the notebook; just a convention as described by the description. Right now there is nothing that will throw an error if a notebook has more than one cell with the same name. 

I'm honestly not sure how we would implement this constraint… it seems like it cannot be expressed in a json schema (or even in jsonld; I'm not sure about it… @bollwyvl could you weigh in?). The trick seems to be that the schema cares much more about the properties associated with objects (which gives the structural organisation) and about abstract ideas about the values associated with those properties.

For example, you can constrain a value's type to being an array. And if it were an array you could specify that all of the elements _in that array_ are [unique](https://spacetelescope.github.io/understanding-json-schema/reference/array.html?highlight=unique#uniqueness). But what we need is the ability to say… "for every cell in this notebook, if were to aggregate their "name" values into an array, would that array consist of  unique elements". 

We could add in another step on the validation on the python side here in nbformat… but then the jsonschema is not quite enough to validate that something is a "correct" notebook, you need this additional test. But that will require separate implementations in anything that consumes notebooks in order to be maintained. Unlike with the schema, those implementations could get out of sync & there would be no way of testing them as to whether they were in sync other than whether it tests consistently to the reference implementation on a number of critical examples.

This especially matters if we are going to be able to endorse front-ends to use names as though they were guaranteed to be unique. For example, on the basis of the description I have been suggesting people use names when they want unique identifiers for cells. This came up just this week in discussion with @rgbkrk and @ewmassey about using a name to ensure there is exactly one cell named "parameters" in a notebook (https://github.com/nteract/papermill/issues/30). 

So if I could get people's insights as to how to address this problem… I'd greatly appreciate it.

cc: @minrk @takluyver

**Comment by rgbkrk** [comment]
Its sounding like we can document that it's _expected_ to be unique and that it must be verified outside of json schema validation.
