### ISSUE TITLE
ipython_genutils has been dropped - do not use it

### ISSUE THREAD

**Issue by opoplawski** [jupyter/nbformat#135]
https://pypi.org/project/ipython_genutils/ states:

Pretend this doesn’t exist. Nobody should use it.

**Comment by takluyver** [comment]
IPython and Jupyter are all part of the same project. When it was broken up into separate pieces, there were some miscellaneous utilities which were used across multiple projects, but weren't big enough or polished enough to make a proper package with documentation and guarantees of stability and so on. So they were stuck in `ipython_genutils` with a note indicating that no-one should use it for new code. Possibly the wording of that note was a bit too blunt, but we didn't want other people to start using it and reporting issues with it.

So it's not a bug that nbconvert uses it. The plan is for our own projects to migrate away from it eventually, but it's not urgent, and any change risks breaking things that work now. So it basically only progresses when someone is changing the relevant code anyway.

**Comment by rgbkrk** [comment]
With the latest updates to get nbformat to Python 3 we're just about off of genutils now. I'll open a new issue that outlines all we have left to stop using an extra kitchen sink.
