### ISSUE TITLE
Add webhook for RTD

### ISSUE THREAD

**Issue by willingc** [jupyter/nbformat#140]
@takluyver @minrk Can you add me to the maintainers on RTD and I'll set up the webhook? Thanks.

**Comment by takluyver** [comment]
I've added you and also set up the webhook while I was logged in. Hopefully I've done so correctly :-)

**Comment by willingc** [comment]
Thanks @takluyver. You set up the webhook correctly 👍 I also enabled building of the dot versions of the docs since this seems a repo where it is reasonable access to built docs for 4.0, 4.1, 4.2 ...
