### ISSUE TITLE
Background on lack of `id` in JSON Schemas

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbformat#15]
In trying to understand JSON Schemas as well as trying to pick amongst the available JavaScript json schema validators, I've dealt with the fact that there is no `id` in the nbformat schemas. It's been fine, but I'm guessing by [other writeups like in the json-schema org](https://github.com/json-schema/json-schema/wiki/The-%22id%22-conundrum) that perhaps there was a lengthy discussion about ids.

**Comment by minrk** [comment]
Interesting. After reading that, I still don't see why we would add the `id` field, or what we would add to it. It does seem to suggest that it's all conditional on the presence of id, and the absence of id should always be handled, so I would be surprised if any valid validator had trouble dealing with its absence.

**Comment by rgbkrk** [comment]
Yeah, they all let me register schemas directly. What's been confusing has been trying to pull out sub schemas for validation (e.g. I'd like to validate output objects for Jupyter js output area)
