### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by boileaum** [jupyter/nbformat#150]
Thanks to all contributors!
Version 4.5.0 contains some useful fixes and seems to be ready more than 2 years ago (ddd36681ee59bf7b1059cfeafccb225dbfd1c48f).
Is there any reason for not releasing it?

**Comment by MSeal** [comment]
Some of us were just discussing this before the holidays started. I'm for pushing a release out and getting the many minor improvements out. Ping a subset of the folks that would care @minrk @rgbkrk @mpacer @jasongrout @captainsafia -- any objects to us rolling out a release in the next week or two for 4.5.0?

**Comment by MSeal** [comment]
Also we should probably pin to python 3 only in the build with the end of support for python 2 in a couple days.

**Comment by MSeal** [comment]
From looking back at issues we should jump to 5.0.0 release for the 4.4.x spec -- see https://github.com/jupyter/nbformat/issues/138#issuecomment-519237214

**Comment by captainsafia** [comment]
@MSeal I'm fine with rolling out a release in the new year. Mind posting a quick changelog for folks to scan through?

**Comment by jasongrout** [comment]
> Also we should probably pin to python 3 only in the build with the end of support for python 2 in a couple days.

This is what would warrant a 5.0 package version release. +1.

**Comment by rgbkrk** [comment]
I'm happy to see a 5.0 package version release go out.

**Comment by MSeal** [comment]
Changelog in PR #153

**Comment by MSeal** [comment]
Completed, after a small hiccup with old schema files not being available.

**Comment by jasongrout** [comment]
> with old schema files not being available.

Thanks for taking care of that, and apologies for missing that on #139

**Comment by MSeal** [comment]
> apologies for missing that on #139

Np, I missed it as well and when I tested it I did `pip install -e .` which didn't reproduce the issue.
