### ISSUE TITLE
NotebookValidationError when code is included in markdown block

### ISSUE THREAD

**Issue by gpleiss** [jupyter/nbformat#160]
I have jupyter notebooks that have `tqdm.tqdm_notebook` blocks. After updating to nbformat > 5.0, I get the following error when running nbsphinx:

```bash
NotebookValidationError in examples/04_Variational_and_Approximate_GPs/GP_Regression_with_Uncertain_Inputs.ipynb:
{'model_id': '', 'version_major': 2, 'version_minor': 0} is not valid under any of the given schema
```

That JSON object is the output of a tqdm block. I notice this issue both when trying to run local jupyter notebooks, as well as when I try using `nbsphinx` to convert notebooks into RTD pages.

Sorry - I don't know enough to dig into this issue any further! If it helps:
- Here's the [error from the Travis CI build](https://travis-ci.org/cornellius-gp/gpytorch/jobs/634402898?utm_medium=notification&utm_source=github_status)
- Here's the [notebook in reference](https://github.com/cornellius-gp/gpytorch/blob/master/examples/04_Variational_and_Approximate_GPs/GP_Regression_with_Uncertain_Inputs.ipynb)

**Comment by gpleiss** [comment]
**EDIT** - i made a mistake earlier when I posted the issue. The problem isn't code blocks within markdown; it's tqdm objects. (Issue is updated to reflect this).

**Comment by MSeal** [comment]
Sorry I missed this thread. If you run the notebook through jupyter lab and save it will try to update the version to the latest. I'm not sure if that notebook is actually major version 2 if it'll load at all, but it's likely that it's stored as a version 4 notebook but never had it's metadata updated correctly.

**Comment by gpleiss** [comment]
That does seem to be the case. Thanks for the help!
