### ISSUE TITLE
Notebook Validation Error using nbformat 5.x with notebooks that have widgets

### ISSUE THREAD

**Issue by ketch** [jupyter/nbformat#161]
I'm getting this error when using nbconvert to run notebooks that have widgets in them.  This only occurs after upgrading from nbformat 4.x to 5.0.3.  Here's a full traceback, which you can also peruse at https://travis-ci.org/ketch/riemann_book/jobs/637262913.  The tests there have been running just fine for two years, but started throwing this error after switching to a newer version of nbformat.

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbformat.validate(nbc, relax_add_props=True)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbformat/validator.py", line 277, in validate
    raise error
nbformat.validator.NotebookValidationError: {'version_major': 2, 'version_minor': 0, 'model_id': '1cfed2a3899e49a3af35520ca75e8220'} is not valid under any of the given schemas
Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
On instance['cells'][47]['outputs'][1]['data']['application/vnd.jupyter.widget-view+json']:
{'model_id': '1cfed2a3899e49a3af35520ca75e8220',
 'version_major': 2,
 'version_minor': 0}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/python/3.6.7/lib/python3.6/logging/__init__.py", line 994, in emit
    msg = self.format(record)
  File "/opt/python/3.6.7/lib/python3.6/logging/__init__.py", line 840, in format
    return fmt.format(record)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/traitlets/config/application.py", line 117, in format
    return super(LevelFormatter, self).format(record)
  File "/opt/python/3.6.7/lib/python3.6/logging/__init__.py", line 577, in format
    record.message = record.getMessage()
  File "/opt/python/3.6.7/lib/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/travis/virtualenv/python3.6.7/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 321, in _preprocess
    preprocessor)
Message: 'Notebook is invalid after preprocessor {}'
Arguments: (<nbconvert.preprocessors.execute.ExecutePreprocessor object at 0x7f6f383ca748>,)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jupyter_core/application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 340, in start
    self.convert_notebooks()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 510, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 481, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 410, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbformat.validate(nbc, relax_add_props=True)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbformat/validator.py", line 277, in validate
    raise error
nbformat.validator.NotebookValidationError: {'version_major': 2, 'version_minor': 0, 'model_id': '1cfed2a3899e49a3af35520ca75e8220'} is not valid under any of the given schemas
Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
On instance['cells'][47]['outputs'][1]['data']['application/vnd.jupyter.widget-view+json']:
{'model_id': '1cfed2a3899e49a3af35520ca75e8220',
 'version_major': 2,
 'version_minor': 0}
Traceback (most recent call last):
  File "test.py", line 50, in <module>
    run_tests()
  File "test.py", line 44, in run_tests
    _, errors = _notebook_run(filename)
  File "test.py", line 23, in _notebook_run
    subprocess.check_call(args)
  File "/opt/python/3.6.7/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['jupyter', 'nbconvert', '--to', 'notebook', '--execute', '--ExecutePreprocessor.timeout=60', '--ExecutePreprocessor.kernel_name=python3', '--output', '/tmp/tmp6zp9xx8t.ipynb', 'Euler.ipynb']' returned non-zero exit status 1.
```

**Comment by ketch** [comment]
I don't know much about this but it looks to me like nbformat is latching onto a widget and thinking that its version information is version info for the notebook itself.

**Comment by bollwyvl** [comment]
It looks like the [notebook in question](https://raw.githubusercontent.com/ketch/riemann_book/shorten_lines/Euler.ipynb) is stored in the `4.1` schema, which wouldn't tolerate the "fancy" widget mime type. It's valid on disk, but once it gets your widgets added, it becomes invalid. Older nbformat would probably tolerate it, but a major version bump can cause some trouble, for sure!

Quick fixes would be: 
- open and save all the notebooks once
- see if replacing `"nbformat_minor": 1` with `"nbformat_minor": 4` fixes it, or uncovers entirely new problems (unlikely)
- go back to 4.x if it was working for you!

The stuff built into `nbconvert --nbformat` won't let you migrate between minor versions, and dropping down to v3 to go back up to v4 seems more brittle than changing one number. Perhaps we could offer that.

**Comment by ketch** [comment]
>open and save all the notebooks once

Actually, after updating to nbformat 5.0.3, I couldn't save these notebooks!  That seems like a serious bug of its own.

>see if replacing "nbformat_minor": 1 with "nbformat_minor": 4 fixes it, or uncovers entirely new problems (unlikely)

This appears to have fixed things; thanks!  I hope that future updates won't break things in way that requires manually editing JSON files.

**Comment by bollwyvl** [comment]
No doubt your server was _also_ using the newer nbformat. Any output
information from the error you were getting when trying to save (and with
what client, etc) would be helpful in tracking it down!

**Comment by ketch** [comment]
I don't remember the error message now, and I can't seem to reproduce it.  The "server" was my laptop, and if you'd like I can send you version numbers of any libraries you're interested in.  I'm running OS X 10.13.6 and using Chrome 79.0.3945.117.

**Comment by bollwyvl** [comment]
Sorry: the "notebook" server. By client, i mean Notebook Classic,
JupyterLab, Spyder, CoLab, etc. etc.

Anyhow: as to versions, the output of something like:

conda list

or

pip freeze

depending on how you install Jupyter stuff would help!

**Comment by ketch** [comment]
Here it is:

```
~ » pip freeze
absl-py==0.6.0
alabaster==0.7.11
anytree==2.4.3
appnope==0.1.0
astor==0.7.1
astroid==1.6.4
astropy==3.0.4
atomicwrites==1.2.1
attrs==18.2.0
Babel==2.6.0
backcall==0.1.0
bibliograph.core==1.0.3
bibliograph.parsing==1.0.1
bibliograph.rendering==1.0.2
bleach==2.1.3
blinker==1.4
bookbook==0.2
bqplot==0.11.1
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
clawpack==5.6.15.6.1
Click==7.0
cloudpickle==0.6.1
cmarkgfm==0.4.2
colorama==0.3.9
coverage==4.5.2
cvxpy==1.0.24
cycler==0.10.0
dataclasses==0.6
decorator==4.3.0
dill==0.3.0
docutils==0.14
ecos==2.0.7.post1
entrypoints==0.2.3
flit==1.2.1
future==0.16.0
gast==0.2.0
gitdb2==2.0.3
GitPython==2.1.10
grpcio==1.16.0
gym==0.10.8
h5py==2.8.0
html5lib==1.0.1
idna==2.6
imageio==2.4.1
imagesize==1.0.0
ipydatawidgets==3.2.0
ipykernel==4.8.2
ipyleaflet==0.9.0
ipython==7.11.1
ipython-genutils==0.2.0
ipyvolume==0.5.1
ipywebrtc==0.4.1
ipywidgets==7.5.1
isort==4.3.4
jedi==0.12.0
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.0
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.4
jupyter-nbextensions-configurator==0.4.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
-e git+https://github.com/keras-rl/keras-rl.git@e94ef887f5fb45d800d458f732e707a82c8b9b7d#egg=keras_rl
keyring==15.1.0
kiwisolver==1.0.1
latexcodec==1.0.5
lazy-object-proxy==1.3.1
llvmlite==0.24.0
lxml==4.2.3
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==3.1.1
mccabe==0.6.1
memory-profiler==0.54.0
mistune==0.8.3
more-itertools==4.3.0
mpmath==1.0.0
multiprocess==0.70.8
nbconvert==5.3.1
nbdime==1.0.0
nbformat==5.0.3
nbopen==0.6
nbsphinx==0.3.3
nbstripout==0.3.3
networkx==2.4
-e git+https://github.com/ketch/nodepy.git@a52ea9e7ccc054e4b6214ec2d31c4b2b51d67726#egg=nodepy
nose==1.3.7
notebook==5.5.0
numba==0.39.0
numpy==1.16.2
numpydoc==0.8.0
oset==0.1.3
osqp==0.5.0
packaging==17.1
pandas==0.23.1
pandocfilters==1.4.2
parso==0.2.1
pbr==5.1.0
petsc==3.12.0
petsc4py==3.12.0
pexpect==4.6.0
pickleshare==0.7.4
pilkit==2.0
Pillow==5.2.0
pkginfo==1.4.2
pluggy==0.8.0
prompt-toolkit==3.0.2
protobuf==3.6.1
-e git+https://github.com/andrenarchy/pseudopy.git@fe85e56a5562bacb60c18ebe509e3b7dc54e3254#egg=pseudopy
psutil==5.4.7
ptyprocess==0.5.2
py==1.7.0
pyamg==4.0.0
pybind11==2.2.4
pybtex==0.21
pybtex-docutils==0.2.1
pycodestyle==2.4.0
pycparser==2.19
pyflakes==2.0.0
pyglet==1.3.2
Pygments==2.2.0
pylint==1.9.1
pyparsing==2.2.0
PyQt5==5.9.2
pytest==4.0.1
pytest-cov==2.6.0
pytest-mpl==0.10
python-dateutil==2.7.3
pythreejs==2.0.0
pytoml==0.1.20
pytz==2018.4
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.5.1
qtconsole==4.3.1
QtPy==1.5.2
readme-renderer==22.0
regex==2018.2.21
requests==2.22.0
requests-toolbelt==0.8.0
rope==0.11.0
scipy==1.1.0
scs==2.1.1.post2
seaborn==0.8.1
Send2Trash==1.5.0
Shapely==1.6.4.post2
sigal==1.4.1
simplegeneric==0.8.1
sip==4.19.8
six==1.11.0
smmap2==2.0.3
snowballstemmer==1.2.1
Sphinx==2.2.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-bibtex==1.0.0
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
sphinxcontrib-websupport==1.1.0
spyder==3.3.1
spyder-kernels==0.2.6
stevedore==1.30.0
sympy==1.4
tensorboard==1.11.0
tensorflow==1.11.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
torch==1.2.0
-e git+https://github.com/rtqichen/torchdiffeq.git@3862b4534d7fb97d1320dd93c21c63b9dc0d70fd#egg=torchdiffeq
torchsummary==1.5.1
torchvision==0.2.2.post3
tornado==5.0.2
tqdm==4.26.0
traitlets==4.3.2
traittypes==0.2.1
twine==2.0.0
urllib3==1.22
vanity==2.2.2
virtualenv==16.0.0
virtualenv-clone==0.4.0
virtualenvwrapper==4.8.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.5.1
wrapt==1.10.11
xarray==0.10.9
yt==3.5.0
zope.component==4.4.1
zope.event==4.3.0
zope.interface==4.5.0
zope.schema==4.5.0
```

**Comment by ketch** [comment]
The client is `jupyter notebook`, launched from the command line.  Perhaps this is what you call "Notebook Classic"?

**Comment by MSeal** [comment]
Yes that is Notebook Classic. To repair the issue launch (jupyter lab)[https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html], load the notebook and save it back. This will automatically update the notebook format so classic will be able to load and manipulate the document again. Usually this process is just updating the minor version number as suggested above, but it could include other small changes to fix the notebook in other places as the format changed over the years.

The longer explanation is below:

Essentially nbformat 5 release added validation for the older format versions instead of using the 4.4 format checks regardless of document version. This was causing invalid format issues with nbformat < 5 when evaluating notebook documents, so the newer package is more strict to avoid errors in notebook processing. This caused manipulations of older formats to fail in places where they were succeeding before because those manipulations were likely not actually spec compliant and your notebook was acting like a 4.4 notebook as best it can. The classic notebook server has been in a frozen / undeveloped state for many years, with lab, nteract, colab, and sagemaker making new interfaces.

**Comment by ketch** [comment]
I guess this can be closed.

**Comment by slayoo** [comment]
> I don't remember the error message now, and I can't seem to reproduce it...

I guess it might have looked this way:

![image](https://user-images.githubusercontent.com/89685/74483023-e5393480-4eb5-11ea-9edb-8fd504d8df8d.png)

**Comment by richdevboston** [comment]
> Yes that is Notebook Classic. To repair the issue launch [jupyter lab](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html), load the notebook and save it back. This will automatically update the notebook format so classic will be able to load and manipulate the document again. Usually this process is just updating the minor version number as suggested above, but it could include other small changes to fix the notebook in other places as the format changed over the years.
> 
> The longer explanation is below:
> 
> Essentially nbformat 5 release added validation for the older format versions instead of using the 4.4 format checks regardless of document version. This was causing invalid format issues with nbformat < 5 when evaluating notebook documents, so the newer package is more strict to avoid errors in notebook processing. This caused manipulations of older formats to fail in places where they were succeeding before because those manipulations were likely not actually spec compliant and your notebook was acting like a 4.4 notebook as best it can. The classic notebook server has been in a frozen / undeveloped state for many years, with lab, nteract, colab, and sagemaker making new interfaces.

### **REOPENING:**  

I am reopening this issue, because although a great reply was given that explains things well, we need some type of more automated solution for it. 

I am looking for a bulk conversion approach to convert a batch of "old v4 classic format notebooks"  into the newer JupyterLab format.  

What utility exists to do this, and what are some command line examples to do the bulk conversion?

**Comment by buriy** [comment]
How to reproduce:
 - install jupyter, notebook, tqdm
 - run jupyter notebook.
 - create a new notebook in it
 - save it
 - change its format to v4.1  at the bottom of the notebook .ipynb file:
```
...
 "nbformat": 4,
 "nbformat_minor": 1
}
```
 - reload it
 - write ```
from tqdm.auto import tqdm; 
for i in tqdm.tqdm(range(10)):
    pass
 - run it
 - try to save it again.

**Comment by MSeal** [comment]
> change its format to v4.1 at the bottom of the notebook .ipynb file:
> ...
>  "nbformat": 4,
>  "nbformat_minor": 1
> }

**Comment by MSeal** [comment]
> change its format to v4.1 at the bottom of the notebook .ipynb file:
> ...
>  "nbformat": 4,
>  "nbformat_minor": 1
> }

Are you using old verisons of jupyter packages? I can't reproduce this. When I create a new Notebook with Jupyter Classic it sets the version to:

> ...
>  "nbformat": 4,
>  "nbformat_minor": 4
> }

**Comment by buriy** [comment]
@MSeal yes new files are created with v4.4 , but I have old files with v4.1 on some projects. 
Corrected the description.

**Comment by MSeal** [comment]
Sure, this may be more of a notebook issue rather than an nbformat issue at this point. Lab will move the schema forward, classic notebook is mostly as-it-is codebase so there's not much quality of life improvements going on. This library is just supplying the validation and was erroneously letting invalid schema saves be made before.

You could pretty easily update all the notebooks in a project by doing:

**Comment by buriy** [comment]
@MSeal Sure I can. But should I?
Options shouldn't get more strict on old files as the time goes.
If you support loading old notebooks, don't complain.
If you don't support -- say that to the library, which should handle that for you.
If this was a typical practice in notebooks v4.1 -- don't complain, that's normal.
If this was not, when changing your behaviour, add a ticket for the notebook lib to fix that issue, and provide a way to communicate this from upper level library to nbformat library.
Why users should become the ones who get the error message on their faces when they did nothing wrong?

**Comment by MSeal** [comment]
> @MSeal Sure I can. But should I?

I was just saying it's possible and may not be worth writing into nbformat.

> Options shouldn't get more strict on old files as the time goes.

At some point old versions need to fall off supported paths. Within the same major version should probably be supported, so it doesn't really apply here.

> If this was not, then, when changing your library behaviour, add a ticket for the notebook lib to fix that issue, and provide a way to communicate this from upper level library to nbformat library.

Sure, it just wasn't clear the validation added would cause old notebooks to complain in classic when this was released. This change was contributed from different people at different times. I only ask to be a little understanding that most of us are maintaining this in our free time and there's a lot of projects interconnected we have to track. It would help us if you could open an issue in the other projects even as not all of us work on all the projects. It'd help even more if you had the time to try to make the change in that repo. If you'd be kind enough to open that I can comment if there's clarifying questions needed. Otherwise I can get to doing that later, just time limited on my end.

> Why users should become the ones who get the error message on their faces when they did nothing wrong?

I agree, but it's not like this was malciously done. Matter of fact it was added because there were bugs with loading 4.x versions that were actually 4.x spec instead of 4.4 and causing weird parse errors, rather than a fairly clear "Hey your version is out of date" message where it's not always the right thing to bump the minor version.

Today nbformat doesn't do notebook version updates on client's behalf. Lab auto-upgrades this already, and most things are tested against lab or the headless execution modes like papermill. So there is a clear work-around, and clear guidance for how to remedy the issue as well for both actual old versions and incorrectly version indicators in files.

**Comment by Avinash1419** [comment]
> > see if replacing "nbformat_minor": 1 with "nbformat_minor": 4 fixes it, or uncovers entirely new problems (unlikely)
> 
> This appears to have fixed things; thanks! I hope that future updates won't break things in way that requires manually editing JSON files.

Where can I find the JSON files? I'm using mac, facing the same issue. Not able to make the suggested change (replacing "nbformat_minor": 1 with "nbformat_minor": 4)

**Comment by Avinash1419** [comment]
> Yes that is Notebook Classic. To repair the issue launch [jupyter lab](https://jupyterlab.readthedocs.io/en/stable/getting_started/installation.html), load the notebook and save it back. This will automatically update the notebook format so classic will be able to load and manipulate the document again. Usually this process is just updating the minor version number as suggested above, but it could include other small changes to fix the notebook in other places as the format changed over the years.
> 
> The longer explanation is below:
> 
> Essentially nbformat 5 release added validation for the older format versions instead of using the 4.4 format checks regardless of document version. This was causing invalid format issues with nbformat < 5 when evaluating notebook documents, so the newer package is more strict to avoid errors in notebook processing. This caused manipulations of older formats to fail in places where they were succeeding before because those manipulations were likely not actually spec compliant and your notebook was acting like a 4.4 notebook as best it can. The classic notebook server has been in a frozen / undeveloped state for many years, with lab, nteract, colab, and sagemaker making new interfaces.

Worked for me perfectly. Thanks for the suggestion!!
