### ISSUE TITLE
Add support for jupyter notebook v5.

### ISSUE THREAD

**Issue by TruthSeekerBeast** [jupyter/nbformat#164]
Currently, versions till v4 are supported, however it throws an error when trying to convert a version 5 notebook that version v5 does not exist. I think a v5 with its schema should be added to the versions.

**Comment by MSeal** [comment]
We're still on version 4 schema, there isn't a version 5. The package version being 5.0 is independent of the spec schema which is still at 4.4

**Comment by TruthSeekerBeast** [comment]
But currently, I am getting this error with version 5 jupyter notebooks, and I am kind of stuck on what can I do with it, can you please guide?

```
ValueError at /
Cannot convert notebook to v5 because that version doesn't exist

Exception Value: Cannot convert notebook to v5 because that version doesn't exist
```

**Comment by MSeal** [comment]
Need more details on what you are doing to debug more. But I am guessing you are trying to save a notebook with the major version set to 5.0 somehow and validation is catching that this isn't legal.

**Comment by TruthSeekerBeast** [comment]
The library used to convert the notebook to module does that. However, I have downgraded some library versions and updated requirements with minor fixes. Please take pull again and try it should resolve the issue now.

**Comment by jasongrout** [comment]
To be really clear, there is no notebook format version 5. It doesn't exist. There is only the nbformat *python package version* 5. The notebook file format is still at most 4.4. If something is generating notebook files claiming to have notebook format version 5, it is in error in that software, not in nbformat.

As such, if nbformat is complaining that notebook format version 5 does not exist, nbformat is correct, and the software that generated the notebook should be fixed.

**Comment by MSeal** [comment]
Going to close this issue. If you have follow-up questions feel free to post them still

**Comment by krassowski** [comment]
I run onto this problem with nbimporter. It tries to convert notebook to `nbformat.version_info[0]`. I guess that it should go for `max(nbformat.versions)`, right? Or, is there another public API exposing the most recent version?

**Comment by jasongrout** [comment]
These indicate the current format is version 4.4:

```
In [2]: nbformat.current_nbformat                                                                                                                                       
Out[2]: 4

In [3]: nbformat.current_nbformat_minor                                                                                                                                 
Out[3]: 4
```

**Comment by krassowski** [comment]
Thank you!
