### ISSUE TITLE
Release 5.0.5

### ISSUE THREAD

**Issue by jasongrout** [jupyter/nbformat#168]
@MSeal, @minrk (or whoever else can) - can we have a 5.0.5 release of nbformat that includes https://github.com/jupyter/nbformat/pull/167, so people can stop having issues with noncompliant notebooks with format version 4.1?

**Comment by MSeal** [comment]
Yeah I can do that, was about to kick off a 6.1.2 release for jupyter client as well

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
Hmmm, in https://github.com/sagemathinc/cocalc/issues/4472, @williamstein says that cocalc has been generating notebook format version 4.0 notebooks with widgets displayed in them, and of course they've been working with nbformat package version 4.x. In #167, we only retroactively modified format version 4.1, but perhaps we should also retroactively modify format version 4.0, if those notebooks are also in the wild? @minrk?

**Comment by MSeal** [comment]
I think it's reasonably safe to extend that to 4.0 if you want to PR it

**Comment by jasongrout** [comment]
PR submitted and merged: #169.

Let me ping the steering council about this and report back by Monday before we release these changes. Especially when we are dealing with retroactively changing formats, which is the very foundational layer of Jupyter, it would be good to flag things for wider review or comment.

**Comment by williamstein** [comment]
@jasongrout -- thanks!

**Comment by jasongrout** [comment]
> Let me ping the steering council about this and report back by Monday before we release these changes.

To be clear, this discussion is happening in public on #170, so there is nothing more to report back from a steering council discussion.

**Comment by MSeal** [comment]
@jasongrout I've released 5.0.5 -- however I don't have permissions to the npm package update (for username `mseal`) to promote the json changes to javascript. Someone needs to run `npm publish` while on the `55eae74751416095be97eb19858560b740241aae` commit sha / 5.0.5 tag or add me as a valid user to do so. I'm not sure if you have permissions that in particular or not?

**Comment by jasongrout** [comment]
It looks like @minrk and @rgbkrk are the ones that have permissions to publish https://www.npmjs.com/package/nbformat-schema. I'd also love to have permission to publish that npm package.

**Comment by rgbkrk** [comment]
I'll add you on @jasongrout as well @SylvainCorlay. Anybody else that should be added on to the JS package?

**Comment by rgbkrk** [comment]
Ok I've added quite a few more folks that are maintainers on jupyterlab packages. Let me know if this is sufficient, otherwise feel free to add the people you think should be on the npm package Jason.

**Comment by MSeal** [comment]
Thanks Kyle -- I'll try releasing the npm package now

**Comment by rgbkrk** [comment]
Even though Matt et. al. were added to the npm package, it didn't seem to let him publish. I went ahead and published 5.0.5.

**Comment by MSeal** [comment]
Thanks @rgbkrk  -- Closing this issue as it's fully released now

**Comment by jasongrout** [comment]
Thanks Kyle and Matt!
