### ISSUE TITLE
slack compatibility

### ISSUE THREAD

**Issue by denfromufa** [jupyter/nbformat#17]
is it possible to generate slack compatible markdown or html documents?

I tried creating slack post and it did not seem to be compatible at all.

**Comment by Carreau** [comment]
How do you tried that ? I suppose you used nbconvert (https://github.com/jupyter/nbconvert) 

```
jupyter nbconvert --to markdown Untitled.ipynb  --stdout
```

seem to generate markdown for me. 

See [docs](http://nbconvert.readthedocs.org/en/latest/usage.html)

**Comment by denfromufa** [comment]
I used download as MD feature in jupyter 4.0 and then pasted to slack post
but it is not working.

I think the problem is that multiple versions of markdown syntax exist?

**Comment by Carreau** [comment]
There are some differences between markdowns but mostly consistent. What
was not working ?

**Comment by rgbkrk** [comment]
I :heart: slack, but it has a strange variant of markdown. You're better off uploading an nbconverted HTML through the slack UI.

**Comment by nicktimko** [comment]
Are you talking about Slack.com, "A messaging app for teams"? 

* The Slack on SourceForge is unrelated
* The [linked page](http://sourceforge.net/p/slack/wiki/markdown_syntax) is for SourceForge's wiki system (which does support Markdown)
* Slack.com [does not support Markdown in messages](https://slack.zendesk.com/hc/en-us/articles/202288908-Formatting-your-messages):

> ### Why don’t you use Markdown syntax?

> We're aware that some users would like to see enhanced Markdown options, but we don’t currently plan to support Markdown in Slack messages. The current formatting options — also used by other popular services like Skype and Google Talk — are more accessible to the many users unfamiliar with the Markdown conventions.

> For more formatting options, we suggest composing a Post to share with your team — Markdown is supported!

* That last part is a lie. Posts don't support Markdown, just the same lame formatting as messages (`*bold*`, `_italic_`, `~strike~`) [Witness me](https://slack-files.com/T04HAKY10-F0BBSRHL7-63ac7471ee). Their rendering seems broken anyways, all I see under the "Wrong" header which is supposed to be "**bold** = `*bold*` (should be italics)" is a "*".

**Comment by rgbkrk** [comment]
Closing as unrelated.
