### ISSUE TITLE
Pre-ehancement proposal. Datetime in notebook format. 

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbformat#18]
Having datetieme next to prompt number will most likely allow us to resolve all the case of wether a cell have been Runned or not. In addition to a timestamp for when the kernel was started. 

Thought ?

**Comment by damianavila** [comment]
I like the idea but how you put the datetime next to the prompt without eating more horizontal space? thought? :wink:

**Comment by minrk** [comment]
I've wanted dates in metadata for a long time (that's why they are in all the messages), but the churn in notebooks for re-running without changes would probably be annoying to some (esp. git).

**Comment by Carreau** [comment]
> I like the idea but how you put the datetime next to the prompt without eating more horizontal space?

I didn't plan to show it permanently, but use it as a proxy to mark cell dirty or not. 



> ve wanted dates in metadata for a long time (that's why they are in all the messages), but the churn in notebooks for re-running without changes would probably be annoying to some (esp. git).

That one of the reason to distinguish more "in-memory" vs "on-disk" format.
The dates can be stored "in-memory" by the server as long as the notebook is running. 
If you start a fresh notebook then you can assume all cells are dirty.

**Comment by damianavila** [comment]
> I didn't plan to show it permanently, but use it as a proxy to mark cell dirty or not.

Oh... now it makes more sense to me...

**Comment by aaronbarzilai** [comment]
Not sure if this is the right spot to mention this, but I'd love to see datetime in notebooks for cells as well.  Perhaps StartDateTime, EndDateTime, and Duration could be shown hidden as a third element below the code but above the result (or just after the result) for each cell.  In the same way "o" is a keyboard shortcut to show/hide the output, "t" could show/hide the timing info.  It would then be great to have a notebook wide control as well to show/hide all the datetimestamps.

Thanks,
Aaron

**Comment by akhmerov** [comment]
> I've wanted dates in metadata for a long time (that's why they are in all the messages), but the churn in notebooks for re-running without changes would probably be annoying to some (esp. git).

Now `ClearOutputPreprocessor` and/or `nbdime` can deal with extra noise better, plus the input/output number is already polluting git history. The usefulness of storing datetime strongly depends on the UI though.

**Comment by rgbkrk** [comment]
Closing. This is probably better off on the [jupyter discourse](https://discourse.jupyter.org/).
