### ISSUE TITLE
nbformat package hangs `pip list -o` !?!

### ISSUE THREAD

**Issue by stonebig** [jupyter/nbformat#19]
hello,

I have this issue https://github.com/pypa/pip/issues/3148#issuecomment-144626421

did you notice it also ? an idea ?

(I'm on Windows 7, wheel may com from Pypi or cgohlke, this never happened before)

**Comment by minrk** [comment]
My guess is it's a network issue, and likely an intermittent one. Installing with pip is working just fine everywhere I have been able to test.

**Comment by stonebig** [comment]
it is an issue with pip cache as `pip list -o --no-cache-dir` works. closing
