### ISSUE TITLE
Long validations times, explore using fastjsonschema

### ISSUE THREAD

**Issue by goanpeca** [jupyter/nbformat#190]
Hello :-) 

On some cases using JLab, when outputs are collected from several nodes (using dask for example) when errors are found, many tracebacks can populate the output of a given cell. In these cases where the output is a large list of tracebacks, the validation step can be significant.

This is a synthetic notebook, but it illustrates the problem.
[50000-errors.ipynb.zip](https://github.com/jupyter/nbformat/files/5269339/50000-errors.ipynb.zip)

A script to test this.

Read is already doing validation, so that extra call to validation was for testing purposes.

```python
import nbformat
import time

TEST_FILE = '50000-errors.ipynb'


def test():
    as_version = 4
    start_time = time.time()
    print("Start:\t0.00")

    with open(TEST_FILE, 'r', encoding='utf-8') as f:
        model = nbformat.read(f, as_version=as_version)

    print("Open:\t"+ str(round(time.time() - start_time, 2)))

    nbformat.validate(model)
    print("Valid:\t"+ str(round(time.time() - start_time, 2)))


if __name__ == "__main__":
    test()
```

Yields in seconds:

```
Start:   0.00
Open:   10.78
Valid:  21.0
```

Could the use of another validation library like https://github.com/horejsek/python-fastjsonschema be considered to improve the validation performance for cases like the one described?

Thanks!

Pinging @mlucool, @echarles

**Comment by MSeal** [comment]
While I'm not opposed to the idea, validating a 33MB notebook begs the question of why is the notebook that large? Other mechanisms start failing for notebooks larger than 10MB (browser crash, transport mechanisms times out, etc).

**Comment by goanpeca** [comment]
@MSeal it was an example to really expose the problem.

>notebook begs the question of why is the notebook that large?

That is a different issue.

>Other mechanisms start failing for notebooks larger than 10MB (browser crash, transport mechanisms times out, etc).

Also a different issue.

>While I'm not opposed to the idea,

Great, I have an opened PR, need to generalize it for the use with other available libraries, and then it would be good for review.

**Comment by MSeal** [comment]
Understood. I'll try to take a look -- protip if you reference this issue in the PR it will generate a link between them and post here that it is linked.

**Comment by goanpeca** [comment]
>if you reference this issue in the PR it will generate a link between them and post here that it is linked.

Yes, I forgot 🙃
