### ISSUE TITLE
Prepare next release 5.1

### ISSUE THREAD

**Issue by willingc** [jupyter/nbformat#199]
@MSeal @goanpeca Let's work on getting the next release out.

Create a release which includes:
- nbformat v4.5 Cell ID #189 
- enhancement for minor version validation #196 (Needs PR)
- fix default validator for a fastjsonschema regression #198
- CI improvements #195 
- PRs merged since last release

Let's bump the release number to 5.1 due to the cell id addition.

Action items:
- [x] Merge #189
- [ ] PR for #196 
- [x] Completion of #195 draft PR
- [x] Changelog updates
- [x] Create a beta release 5.1.0b1
- [x] Release to 5.1.0

cc/ @minrk @rgbkrk

**Comment by goanpeca** [comment]
@willingc sounds good. Will take a look at the release PR again, so we can test it :)

**Comment by MSeal** [comment]
I did a release for 5.1.0 just now. I missed #196 thinking that improvement had been done. Let's add that functionality and get a patch release going for that improvement alone. I'm going to close this issue and focus on that through the open issue instead.

**Comment by MSeal** [comment]
PR for missing improvement: https://github.com/jupyter/nbformat/pull/205

**Comment by MSeal** [comment]
5.1.1 is out #196 fixed
