### ISSUE TITLE
comms and notebook upgrade.

### ISSUE THREAD

**Issue by Carreau** [jupyter/nbformat#2]
mostly a reminder to investigate, discussed in person at BIDS with  @jiahao

But it seem that auto-upgrade notebook  on 3.x might breaks comms in a weird way by carrying coms id  from one version to another (my best guess).

See historic of [this notebook version](https://github.com/jiahao/ijulia-notebooks/blob/master/2014-08-06-parallel-prefix.ipynb).

**Comment by minrk** [comment]
comm IDs aren't stored in notebooks at all, and 2.x didn't persist anything about widgets anywhere, so I'm not sure what this would be referring to.

**Comment by Carreau** [comment]
Well it looked like comms/widgets were broken in notebooks that were "converted" at open time. Even after rerunning cells. The common point seemed to be the upgrade, so this was my best guess. Might be something else totally.

**Comment by rgbkrk** [comment]
This seems out of scope given where we're at in v4 and where the comms are. Closing for now, feel free to re-open.
