### ISSUE TITLE
Creating Jupyter Notebook Failed. An error occurred while creating a new notebook. Validation error: nbformat_minor

### ISSUE THREAD

**Issue by jwrth** [jupyter/nbformat#204]
Hi, everyone! When I want to create a new file Jupyter gives me the error shown in the following image. Does anybody have an idea what's the reason for it and how I can change it?

I'm not sure if it's connected but the error appears since I tried to export a notebook as html. I tried this first using "File - Download as..." but this gave me an error. It worked then in the terminal using "jupyter nbconvert -to html file.ipynb" but since I did this the validation error appears when I want to create a new file:

![grafik](https://user-images.githubusercontent.com/76480183/102889819-9fe17e00-445b-11eb-9ec8-46c3784f6d39.png)

I get a similar error when I try to work on notebooks that were created before:

![grafik](https://user-images.githubusercontent.com/76480183/102891373-5cd4da00-445e-11eb-9371-a573f4555545.png)

There I managed to solve the error by changing the value for "nbformat_minor" to 4 instead of 2 using a text editor. Therefore, I think the problem lies somehow in this nbformat_minor setting which is set to 2 instead of 4 when I create a new notebook. But I have no idea why this error appears now. I didn't update anything before this error appeared. Is there a way to change the default setting for nbformat_minor? The installed nbformat version is 5.0.8.

I guess it's helpful for you to know the versions of jupyter packages. Here's the output of "jupyter --version":

jupyter core     : 4.6.3
jupyter-notebook : 6.1.5
qtconsole        : 4.7.5
ipython          : 7.19.0
ipykernel        : 5.3.1
jupyter client   : 6.1.5
jupyter lab      : 2.1.5
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 4.3.3

Would be great if anybody could help me out with that! Thanks a lot in advance!
Please let me know if you need any additional information!

**Comment by MSeal** [comment]
Try install nbformat 5.1.1 and saving the notebook first. That might resolve the issue by upgrading the minor version automatically. If that doesn't you can edit the notebook file and change the `nbformat_minor` version field to `4` and it should resolve.

**Comment by jwrth** [comment]
A complete reinstallation of Jupyter solved the problem in the end. nbformat is still in the version 5.0.8. so I think it was another package that caused the problem. Thanks anyway for the answer!
