### ISSUE TITLE
Sampling from a set is deprecated

### ISSUE THREAD

**Issue by jaraco** [jupyter/nbformat#212]
While [creating a notebook for testing using nbformat](https://github.com/jaraco/pip-run/blob/c5cb46607cc36fec43b8fb433bfbf976102db58f/pip_run/tests/test_scripts.py#L90-L108), I see this warning in the logs:

```
pip_run/tests/test_scripts.py: 14 warnings
  /Users/jaraco/code/main/pip-run/.tox/python/lib/python3.9/site-packages/nbformat/corpus/words.py:20: DeprecationWarning: Sampling from a set deprecated
  since Python 3.9 and will be removed in a subsequent version.
    return '-'.join((random.sample(acceptable_adjectives(), 1)[0], random.sample(acceptable_nouns(), 1)[0]))
```

**Comment by MSeal** [comment]
Thanks for reporting! If someone is looking for an easy contribution to the project this is a good candidate task

**Comment by mwouts** [comment]
Hi @MSeal , changing the sets to lists seems to fix the issue. In the PR, I have added
- a warning interception to make sure that creating ids don't cause any warning
- an a test to make sure that there are no duplicate words or adjectives
