### ISSUE TITLE
test files missing in nbformat-5.1.2.tar.gz

### ISSUE THREAD

**Issue by arunpersaud** [jupyter/nbformat#213]
Hi

just trying to package this for openSUSE, but I'm getting the following error when using the pypi tar ball (preferred option)

=================================== FAILURES ===================================
[   54s] __________________________ test_upgrade_v4_to_4_dot_5 __________________________
[   54s] 
[   54s]     def test_upgrade_v4_to_4_dot_5():
[   54s]         here = os.path.dirname(__file__)
[   54s] >       with io.open(os.path.join(here, os.pardir, os.pardir, 'tests', "test4.ipynb"), encoding='utf-8') as f:
[   54s] E       FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/nbformat-5.1.2/nbformat/v4/tests/../../tests/test4.ipynb'
[   54s] 
[   54s] nbformat/v4/tests/test_convert.py:82: FileNotFoundError
[   54s] _____________________________ test_sample_notebook _____________________________

Seems as if the tests are there, but the 'test' directory is missing. Can these be included again in the next release?

Thanks

Arun

**Comment by MSeal** [comment]
Sure we can fix that. I forgot we were bundling the tests in the package tbh so I never double checked on their fixtures being included.

**Comment by opoplawski** [comment]
This is still an issue with 5.1.3.  I'm working on updating the Fedora package and hitting this.
