### ISSUE TITLE
Re-introduce english words to cell IDs

### ISSUE THREAD

**Issue by choldgraf** [jupyter/nbformat#226]
# Background

In #216 we decided that the "english-friendly" word lists that we were using to generate cell IDs were problematic because certain combinations could be used in a manner that were derogatory or otherwise problematic. We could not find a suitable alternative, so opted for randomly-generated IDs instead.

Recently @betatim shared with me a reference to the [glitch word repository](https://github.com/glitchdotcom/friendly-words) which seems like it could be a good word list to use if we wish to re-instate english-friendly words. 

It is MIT-licensed, and the README describes this process for choosing their words:

> The words are pulled from curated files. We want the words and their pairings to be friendly, positive, inspiring, whimsical, memorable, etc. They should also be words that most people can easily remember and spell.
>
> All of the words and their generated pairings should be safe for children of all cultures. This means that we permit absolutely no word pairings that invoke to hate speech, hostility, derogatory terms, etc.
> 
> Despite our best efforts, it's easy for a pair of benign words to be combined into something inappropriate. Whenever we notice a generated pair that is problematic, we'll remove at least one of the words from that pair so that it won't reoccur. We'll err on the side of trusting reports and removing potentially inappropriate words rather than defending the appropriate uses of a word.
> 
> When adding words to the list, an abundance of common sense is required. If the word can be used as a slang term for an ethnicity or nationality, there's probably a context where it'll pair up with a verb or adjective that can make it feel unwelcome... so be mindful and avoid those.

**Comment by westurner** [comment]
Benign and *hopefully as latent content free* as such a usability change might be, it is or would be distracting and unnecessary.

**Comment by westurner** [comment]
Edit:

```python
nb["green-ideas-furiously"] # variable declarations
nb["dont-pink-elephant-this-book"] # pd.read_csv
nb["clean-language-cognitive-metaphor"] # display(output["summary_table"])

# or
nb["jgdd543"] # variable declarations
nb["64abcf=\+"] # pd.read_csv
nb[uuid.uuid4()] # display(output["summary_table"])
```

**Comment by jasongrout-db** [comment]
I agree with Wes: I think we should not use english words as ids. I think ids are largely invisible to the user, and the potential for a problem is too great. Besides, why should we use english words when Jupyter notebooks are used all around the world?

**Comment by choldgraf** [comment]
I don't feel strongly about this and unless somebody suggests a strong reason this would be beneficial, i think we should close it

**Comment by krassowski** [comment]
Is this a duplicate of #218?

**Comment by choldgraf** [comment]
Not sure - but I'm just going to close this anyway because it seems like there isn't agreement that it's a good idea in the first place.
