### ISSUE TITLE
nbformat errors with jsonschema 4.4.0

### ISSUE THREAD

**Issue by moorepants** [jupyter/nbformat#248]
I have jsonschema 4.4.0 and this occurs:
```
$ conda env list
Traceback (most recent call last):
  File "/home/moorepants/miniconda/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 44, in <module>
    from . import main_create
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 19, in <module>
    from .. import exceptions, specs
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 9, in <module>
    from .notebook import NotebookSpec
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/conda_env/specs/notebook.py", line 5, in <module>
    import nbformat
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/__init__.py", line 32, in <module>
    from .validator import validate, ValidationError
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/validator.py", line 12, in <module>
    from .json_compat import get_current_validator, ValidationError
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/nbformat/json_compat.py", line 10, in <module>
    import jsonschema
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/__init__.py", line 29, in <module>
    from jsonschema.protocols import Validator
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/protocols.py", line 33, in <module>
    from jsonschema.validators import RefResolver
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/validators.py", line 356, in <module>
    meta_schema=_utils.load_schema("draft3"),
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jsonschema/_utils.py", line 60, in load_schema
    path = resources.files(__package__).joinpath(f"schemas/{name}.json")
AttributeError: module 'importlib_resources' has no attribute 'files'
```

If I downgrade to jsonschema 3.2.0, conda env commands work. This seems to be an issue that nbformat may not be working with newer jsonschema versions.

Issue over at conda: https://github.com/conda/conda/issues/11270
and jsonschema: https://github.com/Julian/jsonschema/issues/921

**Comment by bollwyvl** [comment]
The full output of `pip freeze` and `conda list` would be helpful.

**Comment by moorepants** [comment]
All the conda info is here: https://github.com/conda/conda/issues/11270

**Comment by moorepants** [comment]
Also some relevant info here: https://github.com/Julian/jsonschema/issues/921

**Comment by bollwyvl** [comment]
> All the conda info

If you have ever done any `pip` stuff to that env (e.g. `pip install -e .` something under development) , the other listings may also be relevant: from the listing over there, I don't see any problems, and that version of `nbformat` has been out for 10 months.

For reference, I can't re-create the issue with `conda` or `mamba` starting from this file:

```yaml
# environment.yml
channels:
- conda-forge
- nodefaults
dependencies:
- python =3.7
- pip
- conda
- nbformat
- jsonschema
```

<details>
<summary>pip list</summary>
<pre>
./.foo/bin/pip list
Package                Version
---------------------- ---------
attrs                  21.4.0
brotlipy               0.7.0
certifi                2021.10.8
cffi                   1.15.0
charset-normalizer     2.0.12
colorama               0.4.4
conda                  4.11.0
conda-package-handling 1.7.3
cryptography           36.0.1
idna                   3.3
importlib-metadata     4.11.2
importlib-resources    5.4.0
ipython-genutils       0.2.0
jsonschema             4.4.0
jupyter-core           4.9.2
nbformat               5.1.3
pip                    22.0.3
pycosat                0.6.3
pycparser              2.21
pyOpenSSL              22.0.0
pyrsistent             0.18.1
PySocks                1.7.1
requests               2.27.1
ruamel-yaml-conda      0.15.80
setuptools             60.9.3
six                    1.16.0
tqdm                   4.63.0
traitlets              5.1.1
typing_extensions      4.1.1
urllib3                1.26.8
wheel                  0.37.1
zipp                   3.7.0

</pre>
</details>

<details>
<summary>conda list</summary>
<pre>
# packages in environment at /tmp/foo/.foo:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge  
_openmp_mutex             4.5                       1_gnu  
attrs                     21.4.0             pyhd8ed1ab_0  
brotlipy                  0.7.0           py37h5e8e339_1003  
ca-certificates           2021.10.8            ha878542_0  
certifi                   2021.10.8        py37h89c1867_1  
cffi                      1.15.0           py37h036bc23_0  
charset-normalizer        2.0.12             pyhd8ed1ab_0  
colorama                  0.4.4              pyh9f0ad1d_0  
conda                     4.11.0           py37h89c1867_0  
conda-package-handling    1.7.3            py37h5e8e339_1  
cryptography              36.0.1           py37hf1a17b8_0  
idna                      3.3                pyhd8ed1ab_0  
importlib-metadata        4.11.2           py37h89c1867_0  
importlib_resources       5.4.0              pyhd8ed1ab_0  
ipython_genutils          0.2.0                      py_1  
jsonschema                4.4.0              pyhd8ed1ab_0  
jupyter_core              4.9.2            py37h89c1867_0  
ld_impl_linux-64          2.36.1               hea4e1c9_2  
libffi                    3.4.2                h7f98852_5  
libgcc-ng                 11.2.0              h1d223b6_12  
libgomp                   11.2.0              h1d223b6_12  
libnsl                    2.0.0                h7f98852_0  
libstdcxx-ng              11.2.0              he4da1e4_12  
libzlib                   1.2.11            h36c2ea0_1013  
nbformat                  5.1.3              pyhd8ed1ab_0  
ncurses                   6.3                  h9c3ff4c_0  
openssl                   1.1.1l               h7f98852_0  
pip                       22.0.3             pyhd8ed1ab_0  
pycosat                   0.6.3           py37h5e8e339_1009  
pycparser                 2.21               pyhd8ed1ab_0  
pyopenssl                 22.0.0             pyhd8ed1ab_0  
pyrsistent                0.18.1           py37h5e8e339_0  
pysocks                   1.7.1            py37h89c1867_4  
python                    3.7.12          hb7a2778_100_cpython  
python_abi                3.7                     2_cp37m  
readline                  8.1                  h46c0cb4_0  
requests                  2.27.1             pyhd8ed1ab_0  
ruamel_yaml               0.15.80         py37h5e8e339_1006  
setuptools                60.9.3           py37h89c1867_0  
six                       1.16.0             pyh6c4a22f_0  
sqlite                    3.37.0               h9cd32fc_0  
tk                        8.6.12               h27826a3_0  
tqdm                      4.63.0             pyhd8ed1ab_0  
traitlets                 5.1.1              pyhd8ed1ab_0  
typing_extensions         4.1.1              pyha770c72_0  
urllib3                   1.26.8             pyhd8ed1ab_1  
wheel                     0.37.1             pyhd8ed1ab_0  
xz                        5.2.5                h516909a_1  
yaml                      0.2.5                h7f98852_2  
zipp                      3.7.0              pyhd8ed1ab_1  
zlib                      1.2.11            h36c2ea0_1013  

</pre>
</details>

So it may well be something unrelated to these which is bringing in a bad version of something... but very probably not an `nbformat` problem...

**Comment by moorepants** [comment]
Thanks for checking. I do my best to avoid installing with pip into my base environment, so that should be ok. A conda dev just closed the issue on conda and said I have to downgrade jsonschema. So I opened this https://github.com/conda-forge/conda-feedstock/pull/160 to pin jsonschema in the conda feedstock. Hopefully that is the appropriate fix.

**Comment by moorepants** [comment]
> For reference, I can't re-create the issue with conda or mamba starting from this file:

Well, then maybe downgrading jsonschema isn't the fix...

**Comment by moorepants** [comment]
Notice this in my envionrment:
```
importlib-metadata        4.11.1           py37h89c1867_0    conda-forge
importlib-resources       3.3.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        4.11.1               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
```

There are these two different importlib pacakges, where one is old. I'm not sure why there is the `_` and the `-` version. Are there two versions with different names on conda forge?

**Comment by moorepants** [comment]
You already opened this issue here: https://github.com/conda-forge/importlib_resources-feedstock/issues/46 !

**Comment by moorepants** [comment]
Fix explained here https://github.com/conda/conda/issues/11270.
