### ISSUE TITLE
Add blink1073 to readthedocs

### ISSUE THREAD

**Issue by blink1073** [jupyter/nbformat#261]
@willingc @minrk could one of you please add `blink1073` to https://readthedocs.org/projects/nbformat/?

**Comment by blink1073** [comment]
And also https://readthedocs.org/projects/nbconvert/ while we're at it?

**Comment by willingc** [comment]
@blink1073 You should have access to both now :smile:

**Comment by blink1073** [comment]
Sweet, thanks!  I added the PR Build hooks to both.
