### ISSUE TITLE
pytest should be told to avoid testing nbformat/current.py

### ISSUE THREAD

**Issue by SnarkBoojum** [jupyter/nbformat#274]
It just fails because of the warning...

I propose:
```
Description: don't run pytest on a deprecated file
Author: Julien Puydt
Forwarded: yes

--- nbformat.orig/nbformat/current.py
+++ nbformat/nbformat/current.py
@@ -11,6 +11,9 @@
 import re
 import warnings
 
+import pytest
+pytest.skip('Deprecated')
+
 warnings.warn(
     """nbformat.current is deprecated.
 
```

**Comment by blink1073** [comment]
This was fixed in https://github.com/jupyter/nbformat/pull/260, making a release today.

**Comment by SnarkBoojum** [comment]
Sorry, but I tried to package 5.4.0:
1. removed my patch
2. got the failure again
3. put my patch back
4. didn't see the failure anymore.

So I think there's still something fishy there.

**Comment by blink1073** [comment]
We're using [`testpaths`](https://github.com/jupyter/nbformat/blob/e050631b5eb1531faac3e2eed671574b85c784e4/pyproject.toml#L8) to only use the tests folder.  I don't want to add any notion of `pytest` to the the source files.

**Comment by SnarkBoojum** [comment]
Oh, I now see we had a workaround for a (now fixed) bug, that forced testing everywhere -- if I remove the workaround, there's no need for a patch anymore, and things just work as intended.

Thanks for your help clearing things out!
