### ISSUE TITLE
Jupyter data dir used for NotebookNotary database instead of runtime dir

### ISSUE THREAD

**Issue by jrs65** [jupyter/nbformat#29]
The database used for `NotebookNotary` gets created by default in the Jupyter data directory:

```python
    def _data_dir_default(self):
        app = None
        try:
            if JupyterApp.initialized():
                app = JupyterApp.instance()
        except MultipleInstanceError:
            pass
        if app is None:
            # create an app, without the global instance
            app = JupyterApp()
            app.initialize(argv=[])
        return app.data_dir
```

however, the comments in the code state that it should be the runtime directory

```python

    db_file = Unicode(config=True,
        help="""The sqlite file in which to store notebook signatures.
        By default, this will be in your Jupyter runtime directory.
        You can set it to ':memory:' to disable sqlite writing to the filesystem.
        """)
```

It's not obvious to me which it should be (I'd lean towards the runtime directory), but the code and the help line should at least be consistent so people can set their paths appropriately.

This has bitten me running on a cluster which has a read-only home, so I set the runtime (but not the data) directory to the temporary scratch dir. However this leads it to throw an exception as it creates the notebook (and tries to write to the data dir).

**Comment by minrk** [comment]
I think runtime_dir is the right place. #31 should fix this.

**Comment by minrk** [comment]
Turns out that runtime_dir is probably *not* the right place, in which case updating the docstring is what we should od.
