### ISSUE TITLE
ReadTheDocs is not up to date

### ISSUE THREAD

**Issue by marscher** [jupyter/nbformat#309]
https://nbformat.readthedocs.io/en/latest/changelog.html shows only changes up until 5.3.0, but 5.6.0 is already released.

**Comment by kevin-bates** [comment]
Looks like only the _latest_ version is outdated.  If you select the "latest" dropdown in the lower left corner, you should be able to see the other releases including [_stable_](https://nbformat.readthedocs.io/en/stable/changelog.html) as a workaround for now.  I don't have admin rights to see why _latest_ is not correctly reflected, but I suspect @blink1073 can.

**Comment by blink1073** [comment]
I updated the default branch from master->main, you will need to clear your browser cache to see the update.  I also added you as a maintainer.  :smile:

**Comment by marscher** [comment]
Thanks u guys :)
