### ISSUE TITLE
Release 4.1

### ISSUE THREAD

**Issue by minrk** [jupyter/nbformat#40]
We are all set to release 4.1, which is mostly bugfixes, but it also defines the attachments field and revs the format version to 4.1 from 4.0, a fully backward-compatible addition. To get UI for attachments, users will need notebook-5.0.

I'm inclined to push a final release, as it's been tested in master for a long time, but we can also do a beta cycle if people prefer.

cc @Carreau @ellisonbg @fperez @JamiesHQ @willingc for release process recommendations.

**Comment by takluyver** [comment]
As nobody had weighed in so far, I decided to just do it. 4.1.0 is up on PyPI.

**Comment by fperez** [comment]
Awesome, thanks!!​

**Comment by minrk** [comment]
@takluyver thanks!

**Comment by willingc** [comment]
Thanks @takluyver :D
