### ISSUE TITLE
Custom JSON-based Mimetypes

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbformat#42]
As of nbformat 4.0, application/json is a plain object, which is awesome for JSON-aware diffing and indexing of notebooks. The same thing goes for the message spec with JSON objects.

Let's say you have a custom mime type using a JSON suffix:

* application/vnd.vega.v1+json
* application/vnd.plotly.v1+json

Custom mime types like these can be plain objects according to the message spec, and the intention of a frontend is only to display that which they can support. The way the notebook schema currently handles non-literal application/json is to impose all other mime types to be plain or multiline strings. These objects end up being double encoded, which makes it more painstaking for diffing as well as indexing. This probably wasn't the intent of that section of the schema. See lines https://github.com/jupyter/nbformat/blob/9ffcc3eb19d55cfa7aedd56b57a06d0c0c68ff0c/nbformat/v4/nbformat.v4.schema.json#L355-L365

As we come to extensions within JupyterLab and nteract, I would love to see JSON based custom mime types able to be used as raw JSON.

Related reading:

* [Vega renderer in nteract](https://github.com/nteract/nteract/pull/664)
* [Plotly.js renderer in nteract](https://github.com/nteract/nteract/pull/662)
* [Plotly's Python client adding direct support](https://github.com/plotly/plotly.py/pull/562)
* [nteract's custom mime types proposal](https://github.com/nteract/nteract/issues/670)

**Comment by jasongrout** [comment]
+1 to the idea of treating `...+json` formats special without reencoding them.

**Comment by rgbkrk** [comment]
I'm going to check out updating the types on rendermime followed by either adding geojson as a custom mimetype or a jupyterlab extension.

**Comment by jasongrout** [comment]
> I'm going to check out updating the types on rendermime followed by either adding geojson as a custom mimetype or a jupyterlab extension.

Cool! We already do support a very basic geojson file renderer that is a JLab extension, using leaflet: https://github.com/jupyter/jupyterlab/tree/b29d054461ef96edf11eceee889cd205eabf9b0f/src/leafletwidget (though arguably it should be a third-party extension, not bundled with jlab.)

**Comment by jasongrout** [comment]
> We already do support

Though that support does not extend to rendermime, so you're right that there is still work to do...

**Comment by rgbkrk** [comment]
Yeah, I do love the widget. I'm hoping to support static JSON bundles here.

We should have a conversation about Synchronized Objects as a higher level spec in the message spec proper, outside of the comms API when you have a chance.

**Comment by jasongrout** [comment]
> We should have a conversation about Synchronized Objects as a higher level spec in the message spec proper, outside of the comms API when you have a chance.

+1.
