### ISSUE TITLE
Add JSONLD @context to the top level .ipynb node

### ISSUE THREAD

**Issue by westurner** [jupyter/nbformat#44]
From https://github.com/jupyter/nbformat/pull/43#issuecomment-244806012 :

> JSONLD is `application/ld+json`:
> - https://www.w3.org/TR/json-ld/
> - https://en.wikipedia.org/wiki/JSON-LD
> - https://www.iana.org/assignments/media-types/application/ld+json
> 
> There is a `@context` mapping for nbformat JSONLD out there:
> - https://gist.github.com/bollwyvl/e7f8136bd2ea5674dd00

.
- [x] SCH: .ipynb JSONLD `@context` by @bollwyvl
  - [ ] Would it be okay to merge this upstream?
  - [ ] TST: Does this cover all of the ipynb nbformat v4 attributes?
  - [ ] TST: Tests (`@context + .ipynb => jsonld => rdf`) (PyLD, rdflib-jsonld)
- [ ] Host an @context at a stable, versioned URI
  - `https://<url>/ns/v4/nbformat.context.jsonld`
    - There may be a lot of (cacheable) lookups
      - CDN (GitHub Pages (Fastly), CloudFlare)
  - @ jupyter, what would be the best way to handle this?
- [ ] DOC,SCH: nbformat specification: heading, link(s)?
- [ ] ENH,SCH: Add `@context:` to the top level .ipynb in Jupyter Notebook

Questions:
- Would this be a breaking change?
  - Signatures would change; but otherwise,no, IIUC, adding `@context` to .ipynb would not be a breaking or even a major change, so waiting until nbformat v5 would not be necessary.

**Comment by rgbkrk** [comment]
Well the `@context` is finely encapsulated inside of the payload for application/ld+json. There is no change to the notebook format spec here.

**Comment by westurner** [comment]
Value: Transform Jupyter Notebook JSON (nbformat .ipynb) to JSONLD to RDF (linked data).

http://5stardata.info/

**Comment by westurner** [comment]
> Well the @context is finely encapsulated inside of the payload for application/ld+json. There is no change to the notebook format spec here.

The change to the notebook format spec would be adding ``@context`` to the .ipynb JSON to link to an official JSONLD @context .

**Comment by westurner** [comment]
See:

- #44 Add JSONLD @context to the top level .ipynb node
- #45 Fields for author/creator and title
  - https://github.com/jupyter/nbformat/issues/45#issuecomment-245832510 Example JSONLD for jupyter:JupyterNotebook
    - https://schema.org/name ("title" -> Thing.**name**)
    - https://schema.org/CreativeWork
    - https://schema.org/author
      - https://schema.org/Person +
    - https://schema.org/creator
    - https://schema.org/funder +
      - https://schema.org/Organization +
    - https://schema.org/license +
    - jupyter:JupyterNotebook < (CreativeWork < Thing,  )

- #60 Draft spec for capturing a notebook environment
- #81 Rethinking kernel specs in notebook metadata

**Comment by rgbkrk** [comment]
This would be a major version bump that would break all the frontends requiring validation (notebook, lab, etc.), so this is a non-starter. Closing. Feel free to open if there's likely development activity around it.

**Comment by bollwyvl** [comment]
Yeah, closing is appropriate. I think the annotation/metadata stuff is
quiet for now, so it's unlikely to get pushed from that angle. It's still
probably a good idea to take things like json-pointer-able items seriously,
but the LD spec has evolved a fair amount to support more of the
challenging items (e.g. mimebundle) without requiring us to change
anything. If a frontend/backend wanted to support a context, they can still
do it out-of-band as an HTTP header.

Actually specifying a `$schema` top-level key is another story...

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/sustainability-of-the-ipynb-nbformat-document-format/3051/2

**Comment by westurner** [comment]
Is it now [almost] possible to use the new features of JSON-LD 1.1 to write a sufficient @context for nbformat 5.1?

Looks like there may be a JSON-LD 1.2/2.0 for RDFstar* support; and possibly whatever is needed to add @context to .ipynb files backward-compatibly and non-breakingly.

Is this the latest draft of a JSON-LD 1.0 @context for nbformat v4?
https://gist.github.com/bollwyvl/09f0241b45fc3a98df8b

**Comment by westurner** [comment]
JSON-LD 1.1 (2020) > "Changes since 1.0 Recommendation of 16 January 2014": 
https://www.w3.org/TR/json-ld11/#changes-from-10
