### ISSUE TITLE
Fields for author/creator and title

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbformat#45]
To better behave as published documents, it would be great to have standardized (if not optional) fields for:
- [x] Author/creator
- [x] Title

There are two ways that people are currently "interpreting" both title and author now - the filename (when an on disk format; hint: distributed content stores may not have same mechanics) or the "first" heading of a Markdown cell. The author is thought of from the content source, whether it comes from GitHub, JupyterHub. That's not really a spec by any means, which limits the approach for these as published documents.

In a related fashion, it would be great to see:
- [ ] License

Original discussion and related issues:
- https://github.com/ipython/ipython/issues/6073
- https://github.com/jupyter/notebook/issues/791
- https://github.com/jupyter/nbviewer/issues/437

**Comment by westurner** [comment]
http://schema.org/Thing > http://schema.org/CreativeWork > http://schema.org/DigitalDocument > {DigitalNotebook?}

> - author

https://schema.org/author r: [Organization, Person]

- https://schema.org/Organization (.name, .url)
- https://schema.org/Person (.name, .url, .givenName, .familyName, .email, .funder r: [Organization, Person])

> - title

https://schema.org/name r: [Text]

> - license

Should the license text be inlined somehow ?

https://schema.org/license r: [CreativeWork, URL]

- http://schema.org/CreativeWork (.name, .url)
- http://schema.org/URL 

With a (schema.org) JSONLD ``@context``, this metadata could be indexed by search engines:

- https://en.wikipedia.org/wiki/Schema.org
- #44 "Add JSONLD @context to the top level .ipynb node"
  - [ ] Include {name, author, license} in the ``@context``

**Comment by rgbkrk** [comment]
Where's the discussion gone in the past with regards to making the notebook a JSON LD document?

**Comment by westurner** [comment]
Use cases:

Existing: 

- Users can search with schema.org/CreativeWork structured search results
  - name
  - description
  - url
  - ...
  - author, license
- Users can add structured cell metadata with a GUI
  https://github.com/jupyter/notebook/issues/601
  - nbgrader JSON metadata:
    https://github.com/jupyter/nbgrader/issues/478
- Users can add tags to notebook cells
  https://github.com/jupyter-incubator/contentmanagement/issues/18

**Comment by minrk** [comment]
> Where's the discussion gone in the past with regards to making the notebook a JSON LD document?

It hasn't been met with much support, and I don't personally support turning notebooks into JSON-LD documents. However, following an existing spec for what an Author is makes sense to me. Plus, authors probably has to be a list, not a single author. That logically belongs in the top-level notebook metadata:

```javascript
notebook.metadata.authors = [{
    name: 'full name',
    url: '',
    email: '',
    affiliation: '',
},
...
]
```


As for title, I see two ways. I think the from-markdown way is preferable to me as a notebook author, while the title-in-metadata is preferable to me from the nbconvert/etc. perspective. We could add title UI to the notebook, so that editing the metadata is as easy as a cell. We'd have to also decide how much markdown formatting (if any) is allowed in titles. Bold and italics? Line breaks? Math?

**Comment by minrk** [comment]
Same for license: follow [package.json](https://docs.npmjs.com/files/package.json#license) and use [SPDX license keys](https://spdx.org/licenses/)  in `notebook.metadata.license`, with a `"SEE LICENSE IN <filename>"` for uncommon/custom licenses, and not bundling license text.

**Comment by westurner** [comment]
cc'ing here from #46 :

[...]

- Users can specify multiple authors as structured values
- For schema.org, "title" is ``name``  http://schema.org/name

Expressing multiple authors with schema.org JSONLD:

- https://schema.org/CreativeWork
- https://schema.org/author range: {https://schema.org/Person , https://schema.org/Organization }

```jsonld
{"@context": ["http://schema.org/", {"jupyter": "https://jupyter.org/ns/#" }],
 "@type": ["CreativeWork", "jupyter:JupyterNotebook"],
 "metadata": {
   "name": "Jupyter Notebook Title",
   "author": [
       {"@type": "Person",
         "name": "Author 1"},
       {"@type": "Person", 
         "familyName": "lastname",
         "givenName": "firstname",
         "worksFor": {"@type": "Organization", "name": "UniversityXYZ"},
         "affiliation": {"...":"..."},
         "url": "..."}
    ],
    "funder": [{"name": "UniversityXYZ"],
    "license": "https://creativecommons.org/licenses/by-sa/4.0/",
    "license": {"@type": "CreativeWork",
          "name": "CC by-SA 4.0",
          "url": "https://creativecommons.org/licenses/by-sa/4.0/"},
}

```

[...]

**Comment by charlesvardeman** [comment]
First, let me say this would incredibly useful. One other property that might be useful is the ability to attach an ORCID(https://orcid.org) to a notebook. Since the ORCID is dereferencable as JOSNLD.
A nice example from: http://openresearchsoftware.metajnl.com/article/10.5334/jors.by/
{
  “@context”: “http://schema.org”,
  “@type”: “Person”,
  “name”: “Daniel S. Katz”,
  “@id”: “http://orcid.org/0000-0001-5934-7525”
}

**Comment by JamiesHQ** [comment]
@mpacer : this may be of interest

**Comment by westurner** [comment]
@charlesvardeman re: ORCID, metadata'ing notebooks:

From
https://github.com/schemaorg/schemaorg/issues/195#issuecomment-239493428 :

- https://schema.org/description
- https://schema.org/about
- https://schema.org/educationalAlignment

.

- https://schema.org/Course
  - https://schema.org/CourseInstance

.

- @id (JSONLD RDF subject URI)
- https://schema.org/identifier d: Thing

>

**Comment by rgbkrk** [comment]
I'm going to close this since the first two were completed and that was the title of the issue.

**Comment by p2ya** [comment]
@rgbkrk  is there anyway to get access to notebook metadata inside notebook ?
I need to rewrite part of metadata problematically based on the parameters read in notebook cell.

**Comment by westurner** [comment]
> @rgbkrk is there anyway to get access to notebook metadata inside notebook ?
> I need to rewrite part of metadata problematically based on the parameters read in notebook cell.

(This is a separate issue; but it would be nice to be able to specify the metadata as a cell in the document)

Could there be references like these (or is this already a way to mutate the notebook and cell-level metadata from within a cell)?

```python
__nb__.items()
__cell__.items()
```

With nbmeta, I'd like to be able to do something like this and have that data copied into the notebook-level metadata:

```
CreativeWork(
    title="Document Title",
    author=dict(name="Wes Turner", url="..."))

# CreativeWork._repr_html_() would then output RDFa and update the metadata with JSONLD
```
