### ISSUE TITLE
Include nbstripout

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/nbformat#48]
Would it make sense to add the `nbstripout` to nbformat?

What about adding it as a command-line tool?

**Comment by minrk** [comment]
I don't really think so, but it might. I'd like to keep nbformat pretty minimal, and this functionality is already in nbconvert, etc.

**Comment by rgbkrk** [comment]
Agree, I think `nbstripout` is better off as a separate standalone tool.
