### ISSUE TITLE
application/json mime type needs to be expanded to accept any valid JSON

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbformat#57]
We added an `application/json` renderer in nteract. It's a little tree you can expand.

![screen shot 2016-10-09 at 3 34 20 pm](https://cloud.githubusercontent.com/assets/836375/19223171/16340a94-8e37-11e6-9d03-f76d3deedd91.png)

It's awesome, yay! However, top level arrays are explicitly forbidden in the `application/json` mime type in the `nbformat` schema. The message spec specifically allows it though. For instance if you run:

``` python
import IPython.display
IPython.display.JSON([{'x': 2}, {'thing': 3}])
```

then save the notebook you get this error:

![screen shot 2016-10-09 at 3 31 30 pm](https://cloud.githubusercontent.com/assets/836375/19223176/596e26dc-8e37-11e6-8737-d5a95cd00110.png)

The long term answer is to allow any JSON value in the nbformat for `application/json`. However, this is going to require a major version bump of the format, because `application/json` used to be an array of encoded multiline strings.

**Comment by minrk** [comment]
I'd definitely *like* to drop the legacy multi-line string encoding. What that means to me is figuring out the smoothest way to do small-change major revision to nbformat. If we can work out a way to do that, we should be in good shape moving forward for similar changes.
