### ISSUE TITLE
Document functionality for creating notebooks programmatically

### ISSUE THREAD

**Issue by takluyver** [jupyter/nbformat#58]
I just noticed (while responding to jupyter/nbconvert#452) that the functions for building up notebooks (`new_notebook()`, `new_code_cell()`, etc.) are not documented.

**Comment by westurner** [comment]
- https://github.com/jupyter/nbformat/blob/master/nbformat/notebooknode.py
- https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbbase.py
- https://github.com/jupyter/nbformat/blob/master/nbformat/v4/tests/test_nbbase.py
