### ISSUE TITLE
Add language field to nbformat kernelspec?

### ISSUE THREAD

**Issue by blink1073** [jupyter/nbformat#59]
The current nbformat schema lists `name` and `display_name` in the `kernelspec` [metadata](https://github.com/jupyter/nbformat/blob/92a67fbe9b3eec64bb8b7f346e47e855e9944414/nbformat/v4/nbformat.v4.schema.json#L13).  I propose we add `language` as an optional field in `v4.2` and required field in `v5.0`, since we use that information when attempting to find a fallback kernel, and it is already part of the `kernelspec` [API](http://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs).

**Comment by blink1073** [comment]
Ah, I see the information is already available in `language_info`.  It just so happens that the contents manager already adds a `language` field to a notebook when it saves it.

**Comment by rgbkrk** [comment]
Seems we can close this, and so I will. 😄
