### ISSUE TITLE
Clarification on correct format for markdown attachment syntax

### ISSUE THREAD

**Issue by Analect** [jupyter/nbformat#66]
@minrk 
I was trying to get this working today in a version 5 of the notebook running inside JuptyerLab and notice that you are tweaking some stuff related to this [here](https://github.com/jupyter/nbformat/pull/65).

The docs in here suggest this format:

```
{
  "cell_type" : "markdown",
  "metadata" : {},
  "source" : ["Here is an *inline* image ![inline image](attachment:test.png)"],
  "attachments" : {
    "test.png": {
        "image/png" : ["base64-encoded-png-data"]
    }
  }
}
```
whereas back over [here](https://github.com/jupyter/notebook/pull/1659/commits/106f8c7dc81e8920b49e721bed2dc4c85c59d773), it seems to suggest that `attachment://` is used, which I tried below ... as well as the above approach ... neither of which worked for me.  The image below on the left is using the markdown reference to a file in the same folder ... which works fine ... it's the embedded version that I can't get working.

I found that when I manually edited the ipynb file in an editor on JupyterLab, and then re-rendered as a notebook ... it ended up deleting back out the extra meta-data.  Maybe this isn't fully implemented for JuptyerLab?

![image](https://cloud.githubusercontent.com/assets/4063815/20492447/aeaaaae8-b00c-11e6-8e8f-13349c8de6e9.png)

Is there a v5 compatible notebook example file with a working embedded attachment available anywhere as a reference.  I couldn't find anything within the docs or tests of the various repos.

Thanks.

**Comment by vidartf** [comment]
A workaround for #65 which worked for me for something else, was to remove the square brackets outside the base64 encoded png string. That is, `["base64-encoded-png-data"]` -> `"base64-encoded-png-data"`.

**Comment by minrk** [comment]
@Analect the syntax should be a URL, such as `attachment://test.png`. I'll update the docs here. I don't believe JupyterLab supports attachments yet.

There should be no workarounds necessary for #65. The square brackets in the docs are a typo. #65 doesn't change the types of anything when you open a notebook.

**Comment by Analect** [comment]
@minrk ... thanks for clarification ref square brackets.

> I don't believe JupyterLab supports attachments yet.

That would explain why I couldn't get it to work!
It looks like there's no ability to edit cell meta-data in the notebook within JupyterLab either (other than to open the notebook in a text editor, which is probably not recommended!).

Is there anywhere on the various jupyter repos that is tracking what functionalities in Notebook classic have so far been implemented in 'notebook' within JuptyerLab?  I haven't been able to find anything.  I can see cell drag/drop is working within Lab, which is nice, but it would be good to see somewhere the parts that are still missing. Thanks.

**Comment by blink1073** [comment]
Hi @analect, we do not currently have such a feature run-down, but we should.  Do you mind opening an issue with this request?  https://github.com/jupyterlab/jupyterlab/issues

**Comment by mgeier** [comment]
The double slash in attachment URLs is invalid, see https://github.com/jupyter/notebook/issues/1655.
I've provided #77 to fix this.
