### ISSUE TITLE
Problem: attachments aren't mime-bundles

### ISSUE THREAD

**Issue by minrk** [jupyter/nbformat#68]
There's ambiguity in our terminology of mime-bundles. A mime-bundle is effectively the `content` of a `display_data` message, a dict of the form:

```python
{
  'data': {'mime/keys': 'data'}
  'metadata': {...}
}
```

However, our *validation spec* [uses the name](https://github.com/jupyter/nbformat/blob/4.1.0/nbformat/v4/nbformat.v4.schema.json#L235) to refer to the `.data` key of a mime-bundle. I think due to this, the attachments spec added in 4.1 does *not* make attachments a mimebundle, but instead just the `.data` field of a mime-bundle.

I'm not 100% sure what to do about this. It was a small mistake that slipped through, but it has been released (in August). However, only an unreleased version of the notebook implements attachments, so there's room to call it 'provisional' and fix it.

I see our choices as:

1. live with the fact that attachments aren't actually mime-bundles (only real consequence beyond confusing terminology is lacking the ability to specify metadata, such as image size)
1. promote attachments to proper mime-bundles in 4.2
1. promote attachments to proper mime-bundles in 5.0 (whenever that is)

**Comment by rgbkrk** [comment]
This whole time I've been thinking of the `.data` key as the mime bundle since it was a collection of mimetypes. I figured the metadata and what not was extra packaging next to the core mime bundle there.

**Comment by rgbkrk** [comment]
I'm in favor of (1):

> live with the fact that attachments aren't actually mime-bundles (only real consequence beyond confusing terminology is lacking the ability to specify metadata, such as image size)

Since you can specify the size within the markdown (well, markup).

**Comment by minrk** [comment]
Ha! It's never been perfectly clear, which is why we run into things like this. Another resolution (similar to 1) would be to officially declare mimebundle as the mime-keyed dict, and make it clear that display_data messages, pager output, introspection, etc. *contain* a mime-bundle, whereas attachments *are* a mime-bundle. It's still a bit unfortunate that the two differ, but it's not critical.

I would like to try to resolve the ambiguity more decisively than we have done, but that can be all in docs.

**Comment by minrk** [comment]
Let's go with (1), as it's the least disruptive. I'll try to take a pass on the docs, to see if I can clarify that *either* a mime-bundle is the `display_data.data` mime-keyed-dict, or that attachments aren't mime-bundles.

**Comment by minrk** [comment]
Since we're going with (1), I think we're okay.
