### ISSUE TITLE
Post notebook schemas to npm

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/nbformat#70]
I'd love to see the schemas here be posted to npm regularly. Right now I've been sidestepping it with  a package where I simply mirror the contents of the schemas: https://github.com/rgbkrk/nbschema

What I expect to see is that when a release of the python package is done, a release on npm is done as well with, at the very least, a `package.json` and the two current schemas.

**Comment by minrk** [comment]
cc @SylvainCorlay @jasongrout who were just talking about making the schemas available to js (though via public jupyter.org URLs rather than npm package).

Packaging the schemas for js sounds like something people need. Should this be an nteract repo, and jupyter repo, or a package co-published from the existing nbformat repo? I'm least enthusiastic about the last option. I think `nbschema`'s a just-fine package as it is. What do you think should change?

**Comment by SylvainCorlay** [comment]
npm would also make them available on the unpkg cdn.

**Comment by SylvainCorlay** [comment]
Question though, what would be the relationship between the npm package format and the nbformat major and minor numbers?

**Comment by rgbkrk** [comment]
I'm in favor of "a package co-published from the existing nbformat repo", mostly so they stay in sync (favoring Python as the base, the JS export is for convenience). I'm also more than happy to maintain a consistent API that is based off of released specs from nbformat whether in jupyter or nteract.

> Question though, what would be the relationship between the npm package number and the nbformat major and minor numbers?

Good question!

One way to make the interface only get patch updates as the format updates is to explicitly provide access to the schema being targeted:

```js
import nbformat from 'nbformat';

nbformat['v4.1'] // Schema for 4.1
nbformat['v4.2'] // Schema for 4.2
```

Where we make trouble for ourselves is if we support something like:

```js
import { latest } from 'nbformat';
```

Since the interface to "access" the latest is the same, yet the underlying data/contract may have a major or minor bump. If we maintained that as part of the interface, then we would have to bump the major version of the package when the nbformat major version changes and the minor version when the nbformat minor changes. We'd also have to be mindful of the fact that changing the interface to the package itself can update the major version (irrespective of the nbformat version) -- that's expected though, nothing to be paranoid about.

**Comment by takluyver** [comment]
I'm aiming to release 4.3 soon; do we want to do anything for this?

**Comment by minrk** [comment]
I'll take a stab at it, but I think it can wait if you want to release before I've got anything.

**Comment by minrk** [comment]
I've given it a go in #89. If there are any questions about it, I've no problem waiting for the next round.
