### ISSUE TITLE
Doesn't support non-UTF-8 filepaths

### ISSUE THREAD

**Issue by infinity0** [jupyter/nbformat#76]
`nbformat.write` accepts either string paths or file objects for the filename `fp` argument.

For the operating system to work on paths, they must be bytes. So python uses `LC_CTYPE` to implicitly encode string paths into byte paths. However, `nbformat.write` does not allow byte paths, yet also does not explicitly set an encoding for the string paths that it does accept. This results in bugs like vbraun/ExportSageNB#6, which fails when using a unicode string path, but LC_CTYPE is set to a value that doesn't support unicode characters, such as "POSIX".

In a similar way to how I mentioned on that other bug report, you have a few options on how to fix this:

1. Allow `nbformat.write` to accept `byte` filenames.
2. Say that `nbformat.write` can only accept unicode string filenames, and explicitly do `io.open(fp.encode('utf-8'), 'w', encoding='utf-8')`, bypassing `LC_CTYPE`. Note the two encodes here, the latter is for the file *contents* not the filename. This is **not recommended** because people with non-UTF-8 paths in their filesystems won't be able to use nbformat any more.
3. Add a `filename_encoding` param to `nbformat.write`, then do `io.open(fp.encode(filename_encoding), 'w', encoding='utf-8')`.

(edit: fixed the example in (3))

**Comment by vbraun** [comment]
Technically, filenames are byte strings on Linux. Pretending otherwise will always be wrong in some corner cases. Fun facts:
* Filenames need not be UTF-8 decodable
* Unicode codepoint sequences are not unique and OSX uses (a variant of) NFD while everyone in their right mind uses NFC.

**Comment by takluyver** [comment]
And for added fun, filenames on Windows are actually handled as unicode strings, not bytes, and it's possible to make a file that you cannot reference with a bytes path.

I think the right fix here is 1 - allow filenames to be passed as bytes.

**Comment by embray** [comment]
Yes, you can't just say "filenames are bytes".  That said, interfaces that accept filenames should, like those in the Python stdlib, accept bytes for filenames.
