### ISSUE TITLE
Should `from_dict` strip values that should not be persisted?

### ISSUE THREAD

**Issue by blink1073** [jupyter/nbformat#78]
I was unable to get trusted notebook handling to work in JupyterLab, until I noticed that the value being persisted to disk did not include the `orig_nbformat` metadata key.  I released after the fact that the description states that it should [not be persisted]( https://github.com/jupyter/nbformat/blob/a7a2e9369ed952d2ef474716a5e7be000f123661/nbformat/v4/nbformat.v4.schema.json#L59).    If the offending key were removed [here](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L418) instead of in when [writing](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/fileio.py#L294) this could have been avoided.  I am happy to submit a PR if there is agreement.

**Comment by minrk** [comment]
Stripping on both read and write makes sense, to protect readers against writers who have made this mistake.
