### ISSUE TITLE
 Jupyter notebook format depends on the jsonschema package

### ISSUE THREAD

**Issue by marbre** [jupyter/nbformat#9]
The jsonschema package should be added to the requirments.txt:

```
ERROR: Failure: ImportError (No module named 'jsonschema'

    Jupyter notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.
    )

```

**Comment by Carreau** [comment]
dependency is on [setup.py](https://github.com/jupyter/nbformat/blob/master/setup.py#L90-L95) how did you install?

**Comment by takluyver** [comment]
requirements.txt is just a temporary measure while it needs unreleased versions of some of our other packages. We generally do dependencies by specifying them in setup.py, which works when they're uploaded to PyPI. By the time we release, requirements.txt should have gone away.

**Comment by marbre** [comment]
Thanks for the additional information. I just took a look into some of the setup.py's of other jupyter subprojects, which read in the requirements.txt. I am not installing directly via setup.py since I am just starting to setup ebuilds for Gentoo's science overlay.
