### ISSUE TITLE
Update store_signature to check for duplicate signatures

### ISSUE THREAD

**Issue by Madhu94** [jupyter/nbformat#99]
The [store_signature](https://github.com/jupyter/nbformat/blob/master/nbformat/sign.py#L207) method does not check if the signature is already in the store. 

The primary key used here is ``id``, so ``insert or ignore`` isn't really a check for duplicates. I think we should change the query to check if the signature exists first.

Not really an important issue - but still, thoughts ?

**Comment by takluyver** [comment]
That makes sense to me
